#!/usr/bin/env python3

from sys import argv, exit
from math import exp, sqrt, ceil

def maybe(strcrea, y, ver=0):
    if ver == 0:
        return (-strcrea * exp(-y)) - ((4 - 3 * strcrea) / 2 * exp(-2 * y)) - ((2 * strcrea - 4) / 4 * exp(-4 * y))
    else:
        return (strcrea * exp(-y)) + ((4 - 3 * strcrea) * exp(-2 * y)) + ((2 * strcrea - 4) * exp(-4 * y))

def timer(strcrea):
    y = 0.0
    x = 0.0
    while x < 10:
        y += (maybe(strcrea, x, 1) * x / 1000)
        x += 0.001
    return y

def divis(strcrea, strcre2):
    y = 0.0
    x = 0.0
    while x < 100:
        y += (pow(x - strcre2, 2) * maybe(strcrea, x, 1) / 1000)
        x += 0.001
    return sqrt(y)
