#!/usr/bin/env python3

from math import sqrt, exp, pi
import sys

def func1(x, str1, str2):
    return (1 / (sqrt(2 * pi) * str2)) * exp(-((x - str1) ** 2) / (2 * str2 ** 2))

def func205(a, b, str1, str2):
    d = 10000
    h = (b - a) / d
    res = 0
    for d in range(d):
        res += func1(a + d * h, str1, str2) + 4 * func1(a + d * h + h / 2, str1, str2) + func1(a + (d + 1) * h, str1, str2)
    return res * h / 6

def check_errors(strss):
    if len(strss) < 3 or len(strss) > 5:
        return "Invalid"
    try:
        str1 = float(strss[1])
        str2 = float(strss[2])
        if str2 <= 0 or str1 <= 0 or str1 > 200: 
            return "Invalid"
        if len(strss) == 4 or len(strss) == 5:
            IQ1 = int(strss[3])
            if IQ1 > 200 or IQ1 < 0:
                return "Invalid"
        if len(strss) == 5:
            IQ2 = int(strss[4])
            if IQ2 > 200 or IQ2 < 0 or IQ1 == IQ2 or IQ1 > IQ2:
                return "Invalid"
    except ValueError:
        return "Invalid"
    return None

def main():
    error = check_errors(sys.argv)
    if error:
        print(error)
        exit(84)
    str1 = float(sys.argv[1])
    str2 = float(sys.argv[2])
    if len(sys.argv) == 3:
        for d in range(0, 201):
            print("{:.0f} {:.5f}".format(d, func1(d, str1, str2)))
    if len(sys.argv) == 4:
        IQ = int(sys.argv[3])
        IQ1 = 0
        func2051 = func205(IQ, str1, str1, str2)
        func2052 = func205(IQ1, str1, str1, str2)
        print("{:.1f}".format((func2052 - func2051) * 100) + "% of people have an IQ inferior to " + str(IQ))
    if len(sys.argv) == 5:
        IQ1 = int(sys.argv[3])
        IQ2 = int(sys.argv[4])
        func2051 = func205(IQ1, str1, str1, str2)
        func2052 = func205(IQ2, str1, str1, str2)
        print("{:.1f}".format((func2051 - func2052) * 100) + "% of people have an IQ between " + str(IQ1) + " and " + str(IQ2))

if __name__ == "__main__":
    main()
