#!/usr/bin/env python3

import sys
from math import sqrt, exp, pi

def factor1(str1, str2, a, b):
    return sqrt(((str1 + pow(str2, 2)) / b) - pow(a, 2))

def factor2(allin, str2, b):
    return (allin + str2) / b

def main():
    if len(sys.argv) != 5:
        sys.exit(84)
    try:
        b = int(sys.argv[1])
        a = int(sys.argv[2])
        c = int(sys.argv[3])
        d = int(sys.argv[4])
    except ValueError:
        sys.exit(84)
    if b < 0:
        print("Invalid")
        sys.exit(84)
    buffer = ""
    while buffer != "END":
        print("Enter next value: ", end="")
        buffer = input()
        if buffer == "END":
            break
        else:
            try :
                float(buffer)
            except ValueError:
                print("Invalid")
                sys.exit(84)
            str2 = float(buffer)
            allin = a * b
            str1 = (d * d + a * a) * b
            b += 1
            a = factor2(allin, str2, b)
            abc = factor1(str1, str2, a, b)
            c = b / ((b - 1) / c + 1 / str2)
            rayon = sqrt(a**2 + abc**2)
            print("\tNumber of values:\t%.0f" % b)
            print("\tStandard deviation:\t%.2f" % abc)
            print("\tArithmetic mean:\t%.2f" % a)
            print("\tRoot mean square:\t%.2f" % rayon)
            print("\tHarmonic mean:\t\t%.2f" % c)
            print()

if __name__ == '__main__':
    main()
